before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq net-tools
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install: "pip install -r requirements.txt"
script: "sudo netstat -vltn; python manage.py test"
