language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install: "pip install -r requirements.txt"
script: "mkdir -p /etc/sshkm && cp sshkm.conf /etc/sshkm/ && python manage.py test"
